version: "3.3"
services:
  soneveser:
    container_name: "sonos-event-server"
    build: ./docker
    image: leafphp/docker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.soneveser.rule=Host(`api.novacode.cc`)"
      - "traefik.http.routers.soneveser.entrypoints=websecure"
      - "traefik.http.routers.soneveser.tls.certresolver=myresolver"
    networks:
      - traefik_default
    volumes:
      - .:/var/www

networks:
  traefik_default:
    external: true
