version: "3.3"
services:
  soneveser:
    build: ./docker
    image: leafphp/docker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.soneveser.rule=Host(`api.novacode.cc`)"
    networks:
      - traefik_web
    volumes:
      - .:/var/www

networks:
  traefik_web:
    external: true
