version: "3.1"
services:
  application:
    build: ./docker
    image: leafphp/docker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`api.novacode.cc`)"
    networks:
      - traefik_web
    volumes:
      - .:/var/www

networks:
  traefik_web:
    external: true
